version: 2.1

orbs:
  flutter-orb: circleci/flutter@1.1.0

jobs:
  unit_test: 
    docker: 
      - image: cirrusci/flutter
    steps: 
      - checkout
      - run: flutter doctor
      - run: flutter test

workflows:
  test_and_distribute:
    jobs:
      - unit_test